<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class KeyPairController extends Controller
{
    /**
     * Generate a key pair by the client
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\View\View
     */
    public function show(Request $request)
    {
        return view('keypair.generate');
    }

    /**
     * Store a key pair generated by the client.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(Request $request)
    {
        // TODO
    }
}
