<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class KeyPairController extends Controller
{
    /**
     * Generate a key pair by the client
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        return view('keypair.generate');
    }

    /**
     * Store a key pair generated by the client.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        $key = auth()->user()->key()->firstOrNew();
        $key->fill($request->only('context', 'public', 'private'));
        $key->save();

        return response()->json(['success' => true], 200);
    }
}
